package com.trustev.domain.entities;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Test;

public class DetailedDecisionTest extends BaseTest<DetailedDecision> {

    public DetailedDecisionTest() {
        super(DetailedDecision.class);
    }

    @Override
    DetailedDecision generateObject() {
        String json = "{\n"
            + "    \"Authentication\": {\n"
            + "        \"Id\": \"bfdcb529-4b77-4c22-90cc-e79d95f61360|df7eed61-94a1-4732-8087-09788d6a86c4\",\n"
            + "        \"KBA\": {\n"
            + "            \"AnswerUrl\": \"https://app.trustev.com/api/v2.0/case/bfdcb529-4b77-4c22-90cc-e79d95f61360|df7eed61-94a1-4732-8087-09788d6a86c4/authentication/kba\",\n"
            + "            \"MultiPassQuestions\": [{\n"
            + "                    \"Choices\": [{\n"
            + "                            \"Answer\": false,\n"
            + "                            \"ChoiceText\": \"Glen Rock\",\n"
            + "                            \"Id\": 0\n"
            + "                        }, {\n"
            + "                            \"Answer\": false,\n"
            + "                            \"ChoiceText\": \"Jackson\",\n"
            + "                            \"Id\": 1\n"
            + "                        }, {\n"
            + "                            \"Answer\": false,\n"
            + "                            \"ChoiceText\": \"Denver\",\n"
            + "                            \"Id\": 2\n"
            + "                        }, {\n"
            + "                            \"Answer\": false,\n"
            + "                            \"ChoiceText\": \"Highland\",\n"
            + "                            \"Id\": 3\n"
            + "                        }, {\n"
            + "                            \"Answer\": false,\n"
            + "                            \"ChoiceText\": \"None of the Above\",\n"
            + "                            \"Id\": 4\n"
            + "                        }\n"
            + "                    ],\n"
            + "                    \"Id\": 9,\n"
            + "                    \"QuestionText\": \"In which city does James Smith live or own property?\"\n"
            + "                }\n"
            + "            ],\n"
            + "            \"MultiPassStatus\": 0,\n"
            + "            \"Questions\": [{\n"
            + "                    \"Choices\": [{\n"
            + "                            \"Answer\": false,\n"
            + "                            \"ChoiceText\": \"$16000\",\n"
            + "                            \"Id\": 0\n"
            + "                        }, {\n"
            + "                            \"Answer\": false,\n"
            + "                            \"ChoiceText\": \"$25000\",\n"
            + "                            \"Id\": 1\n"
            + "                        }, {\n"
            + "                            \"Answer\": false,\n"
            + "                            \"ChoiceText\": \"$9000\",\n"
            + "                            \"Id\": 2\n"
            + "                        }, {\n"
            + "                            \"Answer\": false,\n"
            + "                            \"ChoiceText\": \"$31000\",\n"
            + "                            \"Id\": 3\n"
            + "                        }, {\n"
            + "                            \"Answer\": false,\n"
            + "                            \"ChoiceText\": \"None of the Above\",\n"
            + "                            \"Id\": 4\n"
            + "                        }\n"
            + "                    ],\n"
            + "                    \"Id\": 23,\n"
            + "                    \"QuestionText\": \"If you have a current auto loan or lease, what was the original amount financed?\"\n"
            + "                }, {\n"
            + "                    \"Choices\": [{\n"
            + "                            \"Answer\": false,\n"
            + "                            \"ChoiceText\": \"New York\",\n"
            + "                            \"Id\": 0\n"
            + "                        }, {\n"
            + "                            \"Answer\": false,\n"
            + "                            \"ChoiceText\": \"Floyd\",\n"
            + "                            \"Id\": 1\n"
            + "                        }, {\n"
            + "                            \"Answer\": false,\n"
            + "                            \"ChoiceText\": \"Warren\",\n"
            + "                            \"Id\": 2\n"
            + "                        }, {\n"
            + "                            \"Answer\": false,\n"
            + "                            \"ChoiceText\": \"Banks\",\n"
            + "                            \"Id\": 3\n"
            + "                        }, {\n"
            + "                            \"Answer\": false,\n"
            + "                            \"ChoiceText\": \"None of the Above\",\n"
            + "                            \"Id\": 4\n"
            + "                        }\n"
            + "                    ],\n"
            + "                    \"Id\": 7,\n"
            + "                    \"QuestionText\": \"In what county do you live?\"\n"
            + "                }, {\n"
            + "                    \"Choices\": [{\n"
            + "                            \"Answer\": false,\n"
            + "                            \"ChoiceText\": \"Tucker\",\n"
            + "                            \"Id\": 0\n"
            + "                        }, {\n"
            + "                            \"Answer\": false,\n"
            + "                            \"ChoiceText\": \"Dallas\",\n"
            + "                            \"Id\": 1\n"
            + "                        }, {\n"
            + "                            \"Answer\": false,\n"
            + "                            \"ChoiceText\": \"Carson\",\n"
            + "                            \"Id\": 2\n"
            + "                        }, {\n"
            + "                            \"Answer\": false,\n"
            + "                            \"ChoiceText\": \"Eastwood\",\n"
            + "                            \"Id\": 3\n"
            + "                        }, {\n"
            + "                            \"Answer\": false,\n"
            + "                            \"ChoiceText\": \"None of the Above\",\n"
            + "                            \"Id\": 4\n"
            + "                        }\n"
            + "                    ],\n"
            + "                    \"Id\": 4,\n"
            + "                    \"QuestionText\": \"From the following list, select the city in which you lived in 2015?\"\n"
            + "                }, {\n"
            + "                    \"Choices\": [{\n"
            + "                            \"Answer\": false,\n"
            + "                            \"ChoiceText\": \"5'3\\\"\",\n"
            + "                            \"Id\": 0\n"
            + "                        }, {\n"
            + "                            \"Answer\": false,\n"
            + "                            \"ChoiceText\": \"6'1\\\"\",\n"
            + "                            \"Id\": 1\n"
            + "                        }, {\n"
            + "                            \"Answer\": false,\n"
            + "                            \"ChoiceText\": \"5'9\\\"\",\n"
            + "                            \"Id\": 2\n"
            + "                        }, {\n"
            + "                            \"Answer\": false,\n"
            + "                            \"ChoiceText\": \"5'7\\\"\",\n"
            + "                            \"Id\": 3\n"
            + "                        }, {\n"
            + "                            \"Answer\": false,\n"
            + "                            \"ChoiceText\": \"None of the Above\",\n"
            + "                            \"Id\": 4\n"
            + "                        }\n"
            + "                    ],\n"
            + "                    \"Id\": 0,\n"
            + "                    \"QuestionText\": \"Approximately how tall are you?\"\n"
            + "                }\n"
            + "            ],\n"
            + "            \"Status\": 0,\n"
            + "            \"Timestamp\": \"2019-08-20T19:03:19.8369669Z\"\n"
            + "        },\n"
            + "        \"OTP\": {\n"
            + "            \"AuthURL\": null,\n"
            + "            \"DeliveryType\": 0,\n"
            + "            \"Language\": 0,\n"
            + "            \"Passcode\": null,\n"
            + "            \"Status\": 7,\n"
            + "            \"Timestamp\": \"0001-01-01T00:00:00Z\"\n"
            + "        },\n"
            + "        \"Timestamp\": \"0001-01-01T00:00:00Z\",\n"
            + "        \"DocumentAuthentication\": {\n"
            + "            \"Id\": \"337ee5b9-8ed6-4795-b929-cefaa00ea14d\",\n"
            + "            \"Url\": null,\n"
            + "            \"Timestamp\": \"2019-08-20T19:03:19.8556265Z\",\n"
            + "            \"Status\": 4\n"
            + "        }\n"
            + "    },\n"
            + "    \"AuthenticatedDataRequest\": null,\n"
            + "    \"CaseId\": \"bfdcb529-4b77-4c22-90cc-e79d95f61360|df7eed61-94a1-4732-8087-09788d6a86c4\",\n"
            + "    \"CaseNumber\": \"11\",\n"
            + "    \"ComputedData\": {\n"
            + "        \"BlackList\": {\n"
            + "            \"CaseType\": 0,\n"
            + "            \"WasAccountNumberHit\": null,\n"
            + "            \"WasBinHit\": null,\n"
            + "            \"WasCustomerIdHit\": null,\n"
            + "            \"WasEmailDomainHit\": null,\n"
            + "            \"WasFullEmailAddressHit\": null,\n"
            + "            \"WasIPHit\": null,\n"
            + "            \"WasPostCodeHit\": null\n"
            + "        },\n"
            + "        \"CaseType\": 0,\n"
            + "        \"Customer\": {\n"
            + "            \"CaseType\": 0,\n"
            + "            \"Email\": {\n"
            + "                \"ContainsDomainIssue\": null,\n"
            + "                \"ContainsMailboxIssue\": null,\n"
            + "                \"ContainsSyntaxIssue\": null,\n"
            + "                \"IsAgeHigh\": null,\n"
            + "                \"IsAgeLow\": null,\n"
            + "                \"IsAgeMedium\": null,\n"
            + "                \"IsDisposable\": null,\n"
            + "                \"IsDomainNotAllowed\": null,\n"
            + "                \"IsPopularityHigh\": null,\n"
            + "                \"IsPopularityLow\": null,\n"
            + "                \"IsPopularityMedium\": null,\n"
            + "                \"IsUserNameNotAllowed\": null,\n"
            + "                \"IsVelocityHigh\": null,\n"
            + "                \"IsVelocityLow\": null,\n"
            + "                \"IsVelocityMedium\": null\n"
            + "            },\n"
            + "            \"HasBadHistory\": false,\n"
            + "            \"HasGoodHistory\": false,\n"
            + "            \"HasSuspiciousHistory\": false,\n"
            + "            \"IsNameAddressCombinationValid\": null,\n"
            + "            \"IsReturningToPlatform\": true\n"
            + "        },\n"
            + "        \"Device\": {\n"
            + "            \"IsFlashEnabled\": null,\n"
            + "            \"IsJavaEnabled\": null,\n"
            + "            \"IsJSEnabled\": false\n"
            + "        },\n"
            + "        \"GreyList\": {\n"
            + "            \"CaseType\": 0,\n"
            + "            \"WasAccountNumberHit\": null,\n"
            + "            \"WasBinHit\": null,\n"
            + "            \"WasCustomerIdHit\": null,\n"
            + "            \"WasEmailDomainHit\": null,\n"
            + "            \"WasFullEmailAddressHit\": null,\n"
            + "            \"WasIPHit\": null,\n"
            + "            \"WasPostCodeHit\": null\n"
            + "        },\n"
            + "        \"Location\": {\n"
            + "            \"BIN\": null,\n"
            + "            \"CaseType\": 0,\n"
            + "            \"IsIPCountryDomestic\": null\n"
            + "        },\n"
            + "        \"Phone\": {\n"
            + "            \"IsPhoneRisky\": null\n"
            + "        },\n"
            + "        \"Transaction\": {\n"
            + "            \"Email\": {\n"
            + "                \"ContainsDomainIssue\": null,\n"
            + "                \"ContainsMailboxIssue\": null,\n"
            + "                \"ContainsSyntaxIssue\": null,\n"
            + "                \"IsAgeHigh\": null,\n"
            + "                \"IsAgeLow\": null,\n"
            + "                \"IsAgeMedium\": null,\n"
            + "                \"IsDisposable\": null,\n"
            + "                \"IsDomainNotAllowed\": null,\n"
            + "                \"IsPopularityHigh\": null,\n"
            + "                \"IsPopularityLow\": null,\n"
            + "                \"IsPopularityMedium\": null,\n"
            + "                \"IsUserNameNotAllowed\": null,\n"
            + "                \"IsVelocityHigh\": null,\n"
            + "                \"IsVelocityLow\": null,\n"
            + "                \"IsVelocityMedium\": null\n"
            + "            }\n"
            + "        },\n"
            + "        \"Velocity\": {\n"
            + "            \"CaseType\": 0,\n"
            + "            \"DecisionsWithin1Hour\": 0,\n"
            + "            \"DecisionsWithin24Hours\": 10,\n"
            + "            \"DecisionsWithin30Days\": 14,\n"
            + "            \"DecisionsWithin7Days\": 13\n"
            + "        },\n"
            + "        \"WhiteList\": {\n"
            + "            \"CaseType\": 0,\n"
            + "            \"WasAccountNumberHit\": null,\n"
            + "            \"WasBinHit\": null,\n"
            + "            \"WasCustomerIdHit\": null,\n"
            + "            \"WasEmailDomainHit\": null,\n"
            + "            \"WasFullEmailAddressHit\": null,\n"
            + "            \"WasIPHit\": null,\n"
            + "            \"WasPostCodeHit\": null\n"
            + "        },\n"
            + "        \"ExtendedDevice\": {\n"
            + "            \"Risk\": null,\n"
            + "            \"PredictiveMlRisk\": null,\n"
            + "            \"IsRegistrationRisky\": null\n"
            + "        }\n"
            + "    },\n"
            + "    \"RawData\": {\n"
            + "        \"BINInformation\": null,\n"
            + "        \"Browser\": null,\n"
            + "        \"CaseType\": 0,\n"
            + "        \"Customer\": {\n"
            + "            \"Emails\": [],\n"
            + "            \"FirstName\": \"AARON\",\n"
            + "            \"LastName\": \"TESTA\",\n"
            + "            \"PhoneNumber\": null,\n"
            + "            \"SocialSecurityNumber\": \"666-01-0001\"\n"
            + "        },\n"
            + "        \"DeviceTag\": null,\n"
            + "        \"IPAddresses\": [],\n"
            + "        \"Location\": null,\n"
            + "        \"NavigatorLanguage\": null,\n"
            + "        \"NavigatorOscpu\": null,\n"
            + "        \"NavigatorPlugins\": null,\n"
            + "        \"OS\": null,\n"
            + "        \"ScreenColorDepth\": null,\n"
            + "        \"ScreenHeight\": null,\n"
            + "        \"ScreenWidth\": null,\n"
            + "        \"Transaction\": null,\n"
            + "        \"TrustevCustomerId\": \"7c4d493e-44cb-4719-ae61-40767bd52605\"\n"
            + "    },\n"
            + "    \"ExtendedDeviceInformation\": null,\n"
            + "    \"IdentityVerificationPayloadUrl\": null,\n"
            + "    \"Comment\": \"Decision for Default\",\n"
            + "    \"Confidence\": 26,\n"
            + "    \"Id\": \"185237a3-88ec-4d54-acd0-22bdc47c3c94\",\n"
            + "    \"Result\": 1,\n"
            + "    \"Score\": 5,\n"
            + "    \"SessionId\": \"bfdcb529-4b77-4c22-90cc-e79d95f61360\",\n"
            + "    \"Timestamp\": \"2019-08-20T19:03:19.6244628Z\",\n"
            + "    \"Type\": 0,\n"
            + "    \"Version\": 315\n"
            + "}\n";


        ObjectMapper mapper = new ObjectMapper();
        try {
            return mapper.readValue(json, DetailedDecision.class);
        } catch (IOException e) {
            throw new RuntimeException("Failed to generate object.");
        }
    }
}
